#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer colorscheme = "gruvbox" colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    # filemanager = "nerdtree"
    # filemanager = "defx"
    debug_level = 0
    lint_engine = "ale"
    # syntastic_go_checkers = ['golint', 'govet', 'golangci-lint']
    go_checkers = ['golangci-lint']
    go_metalinter_autosave = 1
    go_metalinter_autosave_enabled = ['golangci-lint']
    # go_metalinter_enabled = ['vet', 'revive', 'errcheck']
    # go_metalinter_enabled = ['all']
    go_metalinter_command = "golangci-lint"
    go_metalinter_deadline = "3s"
    go_list_type = "quickfix"
    go_fmt_command = "goimports"
    # go_list_type_commands = {"GoBuild": "quickfix"}
    # go_asmfmt_autosave = 0
    go_gopls_staticcheck = 'golangci-lint'

    # syntastic_go_gometalinter_args = ['--enable=errcheck']
    syntastic_go_checkers = ['golangci-lint']
    # syntastic_go_checkers = ['golint', 'govet', 'golangci-lint']
    # syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
    # gopls 的配置选项
    go_diagnostics_level = 2
    go_diagnostics_enabled = 1
    go_highlight_types = 1
    go_jump_to_error = 1
    # 缩进的配置选项
    default_indent = 4
    expand_tab = true

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

# shell 脚本
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

# format的格式化
[[layers]]
    name = "format"

# 核心配置
[[layers]]
    name = "core"
    filetree_show_hidden = true
    enable_smooth_scrolling = true

# language server 的插件
[[layers]]
    name = 'lsp'
    enabled_clients = ['vimls']

[[layers]]
    name = "unite"

# 调试的配置 
[[layers]]
    name = "debug"

# 默认的配置
[[layers]]
    name = "default"

# tools 工具
[[layers]]
    name = 'tools'

# git的配置
[[layers]]
    # gina, fugitive, gita, git
    name = "git"
    # git_plugin = "fugitive"
    git_plugin = "gina"

# github的配置
[[layers]]
    name = "github"

# gtags的配置
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

# version control 控制
[[layers]]
  name = "VersionControl"

[[layers]]
  name = "fzf"

# 代码检查的工具
[[layers]]
  name = "checkers"
  lint_on_the_fly = false
  lint_on_save = true
  show_cursor_error = true

# 多行编辑
[[layers]]
  name = 'edit'
  autosave_timeout = 3000 
  autosave_events = ['InsertLeave', 'TextChanged']

# ===================================================================
# 语言配置
# ===================================================================

# vim 的语法检查
[[layers]]
    name = 'lang#vim'
    auto_generate_doc = true

# golang
[[layers]]
    name = "lang#go"
    go_file_head = [
      '/*',
      "* Auth: yuanzp",
      "* Mail: 1034889856@qq.com",
      '* Create Time: `strftime("%Y-%m-%d %T")`',
      '*/'
    ] 
    buffer_index_type = 2 
    go_interpreter = "/usr/local/bin/go"
    enabled_linters = ['gometalinter']


# markdown 语法支持
[[layers]]
    name = "lang#markdown"
    enableWcwidth = 1
    listItemIndent = 1
    enabled_formater = ['prettier']

# bash语法支持
[[layers]]
  name = "lang#sh"
  bash-file-head = [
      '#!/usr/bin/env bash',
      '# Time: `strftime("%Y-%m-%d %T")`',
      ''
  ]
#

# ===================================================================


# 自定义插件
[[custom_plugins]]
    name = "lilydjwg/colorizer"
    on_cmd = ['ColorHighlight', 'ColorToggle']
    on_func = 'colorizer#ColorToggle'
    merged = false

# 自定义插件
[[custom_plugins]]
    name = "tpope/vim-scriptease"
    merged = false
    on_cmd = "Scriptnames"

# [[custom_plugins]]
    # name = "mg979/vim-visual-multi"
    # on_cmd = ['ColorHighlight', 'ColorToggle']
    # on_func = 'colorizer#ColorToggle'
    # merged = false


[[layers]]
  name = "leaderf"

# 窗口跳转的支持
[[layers]]
  name = "tmux"
